steps:
  - label: "Triggering frontend team pr pipelines"
    agents:
      queue: frontend-team-pr
    env:
      DEBUG: true
    plugins:
      chronotc/monorepo-diff#v1.1.1:
        diff: '.buildkite/scripts/diff.sh ${BUILDKITE_COMMIT}'
        watch:
          - path: 'frontends/angular/'
            config:
              trigger: 'angular-pr'
          - path: 'frontends/react/'
            config:
              trigger: 'react-pr'